// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Etheta_imaginary
arma::cx_vec Etheta_imaginary(double theta, arma::vec x);
RcppExport SEXP _hawkesbow_Etheta_imaginary(SEXP thetaSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Etheta_imaginary(theta, x));
    return rcpp_result_gen;
END_RCPP
}
// inc_gamma_imag
arma::cx_double inc_gamma_imag(double x, double alpha);
RcppExport SEXP _hawkesbow_inc_gamma_imag(SEXP xSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(inc_gamma_imag(x, alpha));
    return rcpp_result_gen;
END_RCPP
}
// E1_imaginary
arma::cx_double E1_imaginary(double x);
RcppExport SEXP _hawkesbow_E1_imaginary(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(E1_imaginary(x));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_HawkesModule();

static const R_CallMethodDef CallEntries[] = {
    {"_hawkesbow_Etheta_imaginary", (DL_FUNC) &_hawkesbow_Etheta_imaginary, 2},
    {"_hawkesbow_inc_gamma_imag", (DL_FUNC) &_hawkesbow_inc_gamma_imag, 2},
    {"_hawkesbow_E1_imaginary", (DL_FUNC) &_hawkesbow_E1_imaginary, 1},
    {"_rcpp_module_boot_HawkesModule", (DL_FUNC) &_rcpp_module_boot_HawkesModule, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_hawkesbow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
