# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export DiscreteData
NULL

#' @export ContinuousData
NULL

#' @export Model
NULL

#' @export Exponential
NULL

#' @export SymmetricExponential
NULL

#' @export PowerLaw
NULL

#' @export Pareto3
NULL

#' @export Pareto2
NULL

#' @export Pareto1
NULL

#' @export Gaussian
NULL

#' @export
inc_gamma_imag <- function(nu, r) {
    .Call('_hawkesbow_inc_gamma_imag', PACKAGE = 'hawkesbow', nu, r)
}

#' @export
E1_imaginary <- function(x) {
    .Call('_hawkesbow_E1_imaginary', PACKAGE = 'hawkesbow', x)
}

