# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export DiscreteData
NULL

#' @export ContinuousData
NULL

#' @export Model
NULL

#' @export Exponential
NULL

#' @export Pareto3
NULL

#' @export Pareto2
NULL

#' @export Pareto1
NULL

